print("Bio Data")
print("Name: Saurav kumar")
print("Mobile:7856898920")
print("Email id:saurafsps7631@gmail.com")
print("Gender:Male")
print("Father's Name:Vidyanand Sharma")
print("Dob:23/07/2005")
print("Education:BCA")
print("Religion:Hindu")
print("Blood group:B+")
print("Place:Indore")
print("Date:13/01/2026")